### ISSUE TITLE
How to make the spectrum pixel by pixel?

### ISSUE THREAD

**Issue by tekkamanmaverick** [jzuhone/pyxsim#11]
Hi John,
I want to make the spectrum of the special the pixel of the image,  not the spectrum of all the events which pyXSIM generates. How can I make that?
Thank you and best wishes.

**Comment by jzuhone** [comment]
@tekkamanmaverick did you figure this out? sorry, I didn't have a good answer for you yet. 

I'm also sorry I haven't been able to get to the light cone issue--it turns out it is not as simple as it sounds.

**Comment by tekkamanmaverick** [comment]
Yes, I've solved it.
However, the light cone issue is still driving me mad. 
I am very happy to learn that pyxsim has fully supported the arepo data.

**Comment by jzuhone** [comment]
@tekkamanmaverick there may be a hacky way to support the Illustris light cones easily, I'll see if I can put it together next week.

I should warn you that X-ray light cones from the original Illustris should not be taken too seriously, since the hot gas mass in cluster and group-sized halos is known to be at least a factor of 3 too small. When the TNG data is released soon it will be better for this purpose.
