### ISSUE TITLE
choosing line of sight 

### ISSUE THREAD

**Issue by Joshuaalbert** [jzuhone/pyxsim#14]
Greetings,

I'm working with Julius Donnert on a project, and we're trying to create simulated Chandra observations from gridded data.
I'm using https://github.com/jdonnert/Sph2Grid to turn Magneticum snapshots (gadgetv2) into gridded HDF5.
Is it possible to control what the viewing angle is during the observation, i.e. along what axis the cluster is viewed.

Do you have a minimal example that would accomplish this simple goal from python?

Thanks in advance.

**Comment by jzuhone** [comment]
Hi @Joshuaalbert,

Since this is more of a pyXSIM question I will answer only here. 

To answer your question from the SOXS issue you posted, pyXSIM works exactly like PHOX in that it loads the grid or particles in once to create the photons, and then allows you to project along as many lines of sight as desired. Once you create the `PhotonList` object, you use the `project_photons` method, and the first argument to this method is the projection direction, which can either be an axis ("x", "y", or "z") or a normal vector, e.g. `[1.0, 2.0, -4.0]`. 

Also, though we can definitely make your gridded HDF5 dataset to work, I should point out that pyXSIM also works with SPH datasets directly (like PHOX), so there is no need to grid it if you don't have to for some other reason. 

Though this example in the pyXSIM documentation uses a grid-based dataset, it should work equally well if you use an SPH dataset with really no differences:

http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim/cookbook/sloshing.html

Try modifying this for your use case and if you have any trouble to let me know.

**Comment by jzuhone** [comment]
@Joshuaalbert did you get this figured out?

**Comment by Joshuaalbert** [comment]
Digging this project up. Here is @MGJvanGroeningen who will work on it.

**Comment by jzuhone** [comment]
Closing the issue since the other issues were closed, please open a new one if necessary.
