### ISSUE TITLE
The radiation from AGNs

### ISSUE THREAD

**Issue by Arppe** [jzuhone/pyxsim#41]
Hi John,

I notice that you used power-law to model the radiation from the each point-sources. However, as far as I know, the AGNs also can produce emission lines. The Fe K alpha lines (~6.4 keV) from the AGNs are very strong in some cases. In addition, the galaxies which are classifed as point-sources are also modeled as power-laws. I think these galaxies which contain hot gas should be modeled as apec-like models.
By the way, I want to know how you determine the redsfhit of a point-source if you have not capture its emission lines.

Thank you.

**Comment by jzuhone** [comment]
Hi @Arppe,

Thanks for raising this issue. There are several things going on here. 

1. First, pyXSIM does not carry out this calculation at all--this is an issue really for SOXS:

https://github.com/lynx-x-ray-observatory/soxs

2. Regarding your main points:

> I notice that you used power-law to model the radiation from the each point-sources. However, as far as I know, the AGNs also can produce emission lines. The Fe K alpha lines (~6.4 keV) from the AGNs are very strong in some case. In addition, the galaxies which are classifed as point-sources are also modeled as power-laws. I think these galaxies which contain hot gas should be modeled as apec-like models.

The goal of the point-source calculation in SOXS is to provide a model for the CXB, both resolved and unresolved. The overall spectrum of the unresolved CXB is very well-approximated by a power law itself. 

As for the resolved sources, it is obviously true that AGNs will have lines and that galaxies will have hot thermal gas. In the low-counts regime, a power-law fit will perform roughly as well as a thermal fit (or a power-law plus lines), and the goal of our calculation is simply to approximate the number of counts in a given source in different bands. For this reason we use the power-law representations for both AGN and galaxies given in [Hickox and Markevitch (2006)](https://ui.adsabs.harvard.edu/abs/2006ApJ...645...95H/abstract), see also [Lehmer et al. (2012)](https://ui.adsabs.harvard.edu/abs/2012ApJ...752...46L/abstract). 

The other reason we do this is computational cost--it is very cost-prohibitive to compute photon energies for the large number of faint galactic sources (which will have very low numbers of counts) using APEC models--it is even cost-prohibitive to do so for a tabulated power-law model (we tried both, it took forever). Note that in order to obtain maximum speed for this calculation we use the analytic forms for the power-law spectra directly and make many optimizations: 

https://github.com/lynx-x-ray-observatory/soxs/blob/c1566086a9bfc583c472b9dbdef083653df065fe/soxs/background/point_sources.py#L211-L243 

So when we model the CXB, we are not interested in the CXB sources per se--we are just looking to provide a realistic enough model so that the contribution of the CXB to the overall background can be quantified for different applications totally unrelated to the CXB itself (e.g., removing the bright and resolved point sources algorithmically and estimating the unresolved contribution to the total background). If one wants to model the properties of such sources accurately, it should be done separately.

> By the way, I want to know how you determine the redsfhit of a point-source if you have not capture its emission lines.

Note that all of the above objectives can be achieved without any reference to redshift at all.

**Comment by Arppe** [comment]
Thank you very much. 
But I still wonder how to determine the redshift of a point-source in the realistic data analysis. Maybe it is not about the modeling. In my opinion, it is critical to source detection. I'm just curious. Thank you.

**Comment by jzuhone** [comment]
Hi @Arppe, 

In the case of a realistic analysis you do need emission lines, so you would need to model sources with emission lines in them from some process (thermal or otherwise). We're just not trying to do that in our CXB model, so this would have to be done separately from that.

**Comment by Arppe** [comment]
Thank you.

**Comment by jzuhone** [comment]
@Arppe if you have any suggestions for how to model the CXB with the features you mentioned above, let me know--we are interested in it.
